name: Graphql
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.6.0
  - anyio=4.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asyncpg=0.29.0
  - bcrypt=4.3.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cffi=1.17.1
  - click=8.1.8
  - cryptography=45.0.3
  - db=6.2.32
  - expat=2.7.1
  - fastapi=0.112.2
  - greenlet=3.1.1
  - h11=0.16.0
  - idna=3.7
  - iniconfig=1.1.1
  - libcxx=14.0.6
  - libdb=6.2.32
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - packaging=24.2
  - passlib=1.7.4
  - pip=25.1
  - pluggy=1.5.0
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pytest=8.3.4
  - python=3.12.11
  - readline=8.2
  - setuptools=78.1.1
  - sniffio=1.3.0
  - sqlalchemy=2.0.39
  - sqlite=3.45.3
  - starlette=0.38.2
  - tk=8.6.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - uvicorn=0.32.1
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - ariadne==0.26.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - graphql-core==3.2.5
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - pytest-asyncio==1.0.0
      - pytest-html==4.1.1
      - pytest-metadata==3.1.1
      - requests==2.32.3
      - urllib3==2.4.0
