name: Graphql
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.6.0
  - anyio=4.7.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - click=8.1.8
  - coverage=7.6.9
  - expat=2.7.1
  - fastapi=0.112.2
  - h11=0.16.0
  - idna=3.7
  - iniconfig=1.1.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - packaging=24.2
  - pip=25.1
  - pluggy=1.5.0
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.12.11
  - readline=8.2
  - requests=2.32.3
  - setuptools=78.1.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.38.2
  - tk=8.6.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - uvicorn=0.32.1
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - ariadne==0.26.2
      - graphql-core==3.2.5
